# Generated by Django 4.1.6 on 2023-02-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('nname', models.CharField(max_length=20)),
                ('rdate', models.DateTimeField()),
                ('lookup', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('ccode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nname', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('loc', models.CharField(max_length=30)),
                ('health', models.CharField(max_length=30)),
                ('recover', models.CharField(max_length=30)),
                ('attack', models.CharField(max_length=30)),
                ('defence', models.CharField(max_length=30)),
                ('resist', models.CharField(max_length=30)),
                ('aspeed', models.CharField(max_length=30)),
                ('mspeed', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('bigimage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13)),
                ('nname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('rname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('build', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_q', models.CharField(max_length=30)),
                ('skill_w', models.CharField(max_length=30)),
                ('skill_e', models.CharField(max_length=30)),
                ('skill_r', models.CharField(max_length=30)),
                ('skill_p', models.CharField(max_length=30)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bang.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bang.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bang.member')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bang.member'),
        ),
    ]
